name: na_tv
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: 1.19.1
  equatable: 2.0.7
  file_picker: 10.1.9
  firebase_core: 3.14.0
  firebase_core_platform_interface: 5.4.0
  firebase_core_web: 2.23.0
  firebase_performance: 0.10.1+7
  firebase_performance_platform_interface: 0.1.5+7
  firebase_performance_web: 0.1.7+13
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_plugin_android_lifecycle: 2.0.28
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: ^6.3.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  timeago: ^3.6.1
  json_path: ^0.7.6
  mime: ^1.0.4
  provider: ^6.1.1
  page_transition: ^2.1.0
  webviewx_plus: ^0.5.1
  simple_gradient_text: ^1.0.0
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  youtube_player_flutter: ^9.1.3
  mime_type: ^1.0.0

dependency_overrides:
  http: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
